### ISSUE TITLE
CF v231 fails staging due to missing consul agent on CC jobs

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/dea-hm-workspace#5]
v231 introduced the requirement to colocate consul_agent with DEA jobs to download blobs from CC via internal DNS.  However the manifest generation tooling for openstack provided in cf-release doesn't properly colocate consul_agent with CC, or configure the consul.agent.services property on the api_zN jobs to register correctly.

**Comment by fraenkel** [comment]
@Amit-PivotalLabs This is a Rel Eng issue. You guys have hardcoded the templates in the openstack stub which is bizarre. See https://github.com/cloudfoundry/cf-release/blob/develop/spec/fixtures/openstack/cf-stub.yml#L149

Reopen if you can explain the rationale why it is still our issue.
